apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-in-existing-vpc
  region: us-west-2

vpc:
  subnets:
    private:
      us-west-2a: { id: subnet-00b0d2a3889b17a4a }
      us-west-2b: { id: subnet-08ff8a65cd624fe88 }
      us-west-2c: { id: subnet-0758a7ed9fa7a5c66 }

nodeGroups:
  - name: ng-1-workers
    labels: { role: workers }
    instanceType: m5.xlarge
    desiredCapacity: 10
    privateNetworking: true
  - name: ng-2-builders
    labels: { role: builders }
    instanceType: m5.xlarge
    desiredCapacity: 2
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true
