apiVersion: v1
kind: Pod
metadata:
  name: jump-pod
spec:
  terminationGracePeriodSeconds: 1
  containers:
  - image: registry.k8s.io/e2e-test-images/jessie-dnsutils:1.7
    name: jump-ctr
    tty: true
    stdin: true
